version: 2.1

orbs:
  slack: circleci/slack@3.3.0

jobs:
  build:
    docker:
      - image: golang:latest
      - image: circleci/mongo

    steps:
      - slack/notify:
          color: '#42e2f4'
          mentions: 'UD75JR0G1'
          message: 'Starting CI/CD on your PR/commit!'
          webhook: 'https://hooks.slack.com/services/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'
      - checkout:
          path: /go/src/shadow
      - run:
          name: Setup Environment & Integrate
          command: |
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            cd /go/src/shadow
            ls
            dep ensure
            cp internal/config/samples/dev.yaml.sample internal/config/dev.yaml
            go build cmd/api/server.go
            echo "CI passed!"
      - slack/approval-notification:
          mentions: 'UD75JR0G1'
          message: 'CI successsfully and waiting for approval!'
          webhook: 'https://hooks.slack.com/services/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'

  deploy_vultr:
    docker:
      - image: kroniak/ssh-client
    steps:
      - run:
          name: Install CURL
          command: apk add curl
      - add_ssh_keys:
          fingerprints:
            - '60:4a:14:05:24:39:e8:32:07:3b:f5:20:8f:ee:d5:23'
      - run:
          name: Add SSH key
          command: ssh-keyscan 139.180.221.43 >> ~/.ssh/known_hosts
      - run:
          name: Deploy to Vultr
          command: ssh root@139.180.221.43 'cd /var/www/go/src/shadow; git pull; dep ensure; pm2 restart shadow'
      - slack/status:
          # fail_only: true
          mentions: 'UD75JR0G1'
          webhook: 'https://hooks.slack.com/services/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'


workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy_vultr:
          requires:
            - build
          filters:
            branches:
              only: master
